"""
    CICASSLib

Low-level Julia bindings to **CICASS** (McQuinn & O'Leary's cosmological
initial-conditions generator that self-consistently includes the baryon–dark-
matter **streaming velocity**; arXiv:1204.1344 / 1204.1345) through its C-ABI
shared library `libcicass_capi.dylib` (built from `cicass/makeCosICs/cicass_capi.cc`
+ the HDF5-free raw writer `capi_out.c` via `cicass/deps/build_cicass_darwin.sh`).

Structurally mirrors `MusicLib`: a `CodeBridge.Bridge` over one `LazyLib` (path via
`ENV["CICASS_LIB"]` or a sibling `cicass/build` default), the `@xcall` macro for the
(single, file-driven) realizer entry point, and a `serve()` worker loop for the
subprocess transport — so CICASS slots into the EnzoNG.jl unified multi-code
framework exactly the way MUSIC/Enzo/RAMSES do.

**Why CICASS, alongside MUSIC and DISCO-DJ.** MUSIC's two-component (gas+DM) ICs
share identical phases and differ only in amplitude — no relative displacement,
no bulk velocity offset. CICASS uniquely carries the Tseliakhovich–Hirata
streaming velocity `v_bc`: a 2D (k⊥, k∥) transfer function (generated by the
`transfer.x` helper) realized into gas and DM with a coherent **bulk velocity
offset** and correct high-redshift (`zstart`≳100) setup.

Two stages, both wrapped here:

1. [`make_tf`](@ref) runs the `transfer.x` helper (GSL-only) to evolve CAMB
   transfer functions forward with `v_bc` into the 2D TF grid CICASS consumes.
2. [`cicass_generate`](@ref) runs the makeCosICs realizer in-process and writes a
   `.cicass` raw dump ({DM particles + gas grid + streaming offset}, HDF5-free)
   that [`read_snapshot`](@ref) loads for injection into Enzo/RAMSES.

The higher-level [`CICASSSpec`](@ref) + [`generate`](@ref) capture a streaming-IC
problem as a typed Julia value and orchestrate both stages.

Build the library with (from a sibling `cicass` checkout):

    bash cicass/deps/build_cicass_darwin.sh   # → cicass/build/{transfer.x,libcicass_capi.dylib}

or run `Pkg.build("CICASSLib")`, which does this best-effort.
"""
module CICASSLib

using Libdl
using CodeBridge
using CodeBridge: @xcall

export CICASSSpec, generate, make_tf, read_snapshot, CICASSSnapshot,
       available, libpath, transfer_path, real_bytes, last_error, version,
       thermal_state, multispecies_fractions, recfast_path

"Shared-library file name for this platform."
libname() = Sys.isapple() ? "libcicass_capi.dylib" : "libcicass_capi.so"

"Absolute path to the sibling `cicass` source checkout (override with ENV[\"CICASS_ROOT\"])."
cicass_root() = get(ENV, "CICASS_ROOT",
    normpath(joinpath(@__DIR__, "..", "..", "..", "..", "cicass")))

# ── the bridge declaration: one lib, one contract ────────────────────────────
const BRIDGE = CodeBridge.Bridge(:cicass, @__MODULE__;
    libs = Dict(:capi => CodeBridge.LazyLib(
        env = "CICASS_LIB",
        # @__DIR__ = CICASS.jl/lib/CICASSLib/src → up 4 → Projects/, then cicass/build/<lib>
        default = normpath(joinpath(@__DIR__, "..", "..", "..", "..", "cicass", "build", libname())),
        hint = "Build it with `bash cicass/deps/build_cicass_darwin.sh`, or set ENV[\"CICASS_LIB\"].")),
    manifest_files = [joinpath(@__DIR__, "CICASSLib.jl")],
    contract_seed = "cicass-bridge-contract-v1")

"Absolute path to the CICASS C-ABI shared library (`ENV[\"CICASS_LIB\"]` or sibling default)."
libpath() = CodeBridge.libpath(BRIDGE)

"True when the CICASS shared library exists on disk."
available() = CodeBridge.available(BRIDGE)

"Absolute path to the `transfer.x` TF-grid helper (`ENV[\"CICASS_TRANSFER\"]` or sibling build dir)."
transfer_path() = get(ENV, "CICASS_TRANSFER",
    normpath(joinpath(cicass_root(), "build", "transfer.x")))

# ── C-ABI surface (see cicass/makeCosICs/cicass_capi.cc) ─────────────────────

"""
    cicass_generate(args::AbstractString) -> Int

Run the CICASS makeCosICs realizer with the space-separated `genICs` flag string
`args` (e.g. `"-L0.2 -V30 -N128 -G128 -Z100 -H0.71 -O0.27 -B0.046 -g<glass> -o. -bout"`).
The realizer reads the TF grid `initSimCartZI<Z>.0_Vbc<V>.0_<N>_<L>.dat` from the
current directory and writes `<out>.cicass`. Returns 0 on success, non-zero on
failure (then [`last_error`](@ref) carries the message).
"""
cicass_generate(args::AbstractString) =
    @xcall(:cicass_generate, Cint, (Cstring,), args)

"Human-readable message for the most recent failed [`cicass_generate`](@ref)."
last_error() = unsafe_string(@xcall(:cicass_last_error, Cstring, ()))

"CICASS code/version string."
version() = unsafe_string(@xcall(:cicass_version, Cstring, ()))

"Bytes per `.cicass` field element (8 = f64; the build default)."
real_bytes() = Int(@xcall(:cicass_real_bytes, Cint, ()))

include("ic.jl")
include("snapshot.jl")
include("thermo.jl")

# ── worker loop (subprocess transport, for multi-code sessions) ──────────────
"""
    serve(; cin=stdin, cout=stdout, shm=ARGS[1])

CodeBridge reference worker loop for the CICASS bridge: spawn
`julia -e 'using CICASSLib; CICASSLib.serve()' <shm>` and drive it from a client
via `CodeBridge.connect_worker!`. CICASS links FFTW/GSL and uses OpenMP, so — like
MUSIC — the worker matters when it shares a session with the live solver codes
(OpenMP/FFTW collisions in a multi-code host).
"""
serve(; cin::IO = stdin, cout::IO = stdout, shm::AbstractString = ARGS[1]) =
    CodeBridge.serve(BRIDGE; cin = cin, cout = cout, shm = shm)

end # module
